-- DROP USER BOOKME CASCADE; 

-- DROP TABLESPACE BOOKME_DATA INCLUDING CONTENTS AND DATAFILES;
-- DROP TABLESPACE BOOKME_TEMP INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE BOOKME_DATA DATAFILE '/u02/app/oracle/oradata/ORCL/BOOKME_DATA.dbf' SIZE 20M REUSE AUTOEXTEND ON NEXT 512K MAXSIZE 8192M;
CREATE TEMPORARY TABLESPACE BOOKME_TEMP TEMPFILE '/u02/app/oracle/oradata/ORCL/BOOKME_TEMP.dbf' SIZE 5M AUTOEXTEND ON;

-- SELECT * FROM V$DATAFILE
-- alter system set DEFERRED_SEGMENT_CREATION=FALSE scope=both; // To include empty tables in export

-- To create user BOOKME without prefix C## in Oracle 12:
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- To disable password expiring
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;

-- USER SQL
CREATE USER BOOKME IDENTIFIED BY PASS123 DEFAULT TABLESPACE "BOOKME_DATA" TEMPORARY TABLESPACE "BOOKME_TEMP";
-- ROLE
GRANT "RESOURCE" TO BOOKME WITH ADMIN OPTION;
GRANT "CONNECT" TO BOOKME WITH ADMIN OPTION;
ALTER USER BOOKME DEFAULT ROLE "RESOURCE","CONNECT";
-- SYSTEM PRIVILEGES
GRANT CREATE SESSION TO BOOKME WITH ADMIN OPTION;
GRANT CREATE TABLE TO BOOKME WITH ADMIN OPTION;
GRANT CREATE PROCEDURE TO BOOKME WITH ADMIN OPTION;
GRANT CREATE SEQUENCE TO BOOKME WITH ADMIN OPTION;
GRANT CREATE ANY TRIGGER TO BOOKME WITH ADMIN OPTION;
GRANT DROP ANY TRIGGER TO BOOKME WITH ADMIN OPTION;
GRANT CREATE ANY INDEX TO BOOKME WITH ADMIN OPTION;
GRANT DROP ANY INDEX TO BOOKME WITH ADMIN OPTION;
GRANT CREATE ANY VIEW TO BOOKME WITH ADMIN OPTION;
GRANT DROP ANY VIEW TO BOOKME WITH ADMIN OPTION;

-- To prevent ora-01950 in Oracle 12:
GRANT UNLIMITED TABLESPACE TO BOOKME;

-- PURGE RECYCLEBIN;
