--
-- Tables
--

CREATE TABLE IF NOT EXISTS PRZ_STRUTTURE (
  ID                INT NOT NULL,
  ID_UTE_INSERT     INT NOT NULL,
  DATA_INSERT       DATE NOT NULL,
  ID_UTE_UPDATE     INT,
  DATA_UPDATE       DATE,
  ID_UTE_DELETE     INT,
  DATA_DELETE       DATE,
  FLAG_ATTIVO       INT DEFAULT 1 NOT NULL,
  ID_GRU            INT NOT NULL,
  ID_AZI            INT,
  ID_FAR            INT,
  CODICE            VARCHAR(10) NOT NULL,
  DESCRIZIONE       VARCHAR(50) NOT NULL,
  TELEFONO          VARCHAR(15),
  EMAIL             VARCHAR(100),
  PREN_ONLINE       INT DEFAULT 0 NOT NULL,
  CHECK_USER_DESK   INT DEFAULT 0 NOT NULL,
  CONSTRAINT PK_PRZ_STRUTTURE PRIMARY KEY (ID) );

CREATE TABLE IF NOT EXISTS PRZ_ATTREZZATURE (
  ID                INT NOT NULL,
  ID_UTE_INSERT     INT NOT NULL,
  DATA_INSERT       DATE NOT NULL,
  ID_UTE_UPDATE     INT,
  DATA_UPDATE       DATE,
  ID_UTE_DELETE     INT,
  DATA_DELETE       DATE,
  FLAG_ATTIVO       INT DEFAULT 1 NOT NULL,
  ID_GRU            INT NOT NULL,
  ID_AZI            INT,
  ID_FAR            INT,
  CODICE            VARCHAR(10) NOT NULL,
  DESCRIZIONE       VARCHAR(50) NOT NULL,
  UBICAZIONE        VARCHAR(100),
  CONSTRAINT PK_PRZ_ATTREZZATURE PRIMARY KEY (ID) );

CREATE TABLE IF NOT EXISTS PRZ_CLIENTI (
  ID                INT NOT NULL,
  ID_UTE_INSERT     INT NOT NULL,
  DATA_INSERT       DATE NOT NULL,
  ID_UTE_UPDATE     INT,
  DATA_UPDATE       DATE,
  ID_UTE_DELETE     INT,
  DATA_DELETE       DATE,
  FLAG_ATTIVO       INT DEFAULT 1 NOT NULL,
  ID_GRU            INT NOT NULL,
  ID_AZI            INT,
  ID_FAR            INT,
  COGNOME           VARCHAR(50) NOT NULL,
  NOME              VARCHAR(50) NOT NULL,
  CODICE_FISCALE    VARCHAR(16),
  SESSO             VARCHAR(1),
  DATA_NASCITA      DATE,
  TELEFONO_1        VARCHAR(18),
  TELEFONO_2        VARCHAR(18),
  EMAIL             VARCHAR(100),
  INDIRIZZO         VARCHAR(100),
  CITTA             VARCHAR(50),
  CAP               VARCHAR(5),
  REPUTAZIONE       INT,
  NOTE              VARCHAR(255),
  ID_FIDELITY       INT,
  UTENTE            VARCHAR(50),
  PASSWORD          VARCHAR(50),
  DIS_PREN_ONLINE   INT,
  CONSTRAINT PK_PRZ_CLIENTI PRIMARY KEY (ID) );

CREATE TABLE IF NOT EXISTS PRZ_COLLABORATORI (
  ID                INT NOT NULL,
  ID_UTE_INSERT     INT NOT NULL,
  DATA_INSERT       DATE NOT NULL,
  ID_UTE_UPDATE     INT,
  DATA_UPDATE       DATE,
  ID_UTE_DELETE     INT,
  DATA_DELETE       DATE,
  FLAG_ATTIVO       INT DEFAULT 1 NOT NULL,
  ID_GRU            INT NOT NULL,
  ID_AZI            INT,
  ID_FAR            INT,
  NOME              VARCHAR(50) NOT NULL,
  COLORE            VARCHAR(6)  NOT NULL,
  PREN_ONLINE       INT DEFAULT 1 NOT NULL,
  ID_UTENTE         INT,
  ORDINE            INT DEFAULT 0,
  VISIBILE          INT DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PRZ_COLLABORATORI PRIMARY KEY (ID) );

CREATE TABLE IF NOT EXISTS PRZ_ATTREZZATURE_RIS (
  ID                INT NOT NULL,
  ID_UTE_INSERT     INT NOT NULL,
  DATA_INSERT       DATE NOT NULL,
  ID_UTE_UPDATE     INT,
  DATA_UPDATE       DATE,
  ID_UTE_DELETE     INT,
  DATA_DELETE       DATE,
  FLAG_ATTIVO       INT DEFAULT 1 NOT NULL,
  ID_ATTREZZATURA   INT,
  ID_COLLABORATORE  INT,
  RISERVATO_DAL     TIMESTAMP,
  RISERVATO_AL      TIMESTAMP,
  CONSTRAINT PK_PRZ_ATTREZZATURE_RIS PRIMARY KEY (ID),
  CONSTRAINT FK_PRZ_ATT_RIS_ATT FOREIGN KEY (ID_ATTREZZATURA) REFERENCES PRZ_ATTREZZATURE(ID),
  CONSTRAINT FK_PRZ_ATT_RIS_COL FOREIGN KEY (ID_COLLABORATORE) REFERENCES PRZ_COLLABORATORI(ID) );

CREATE TABLE IF NOT EXISTS PRZ_PRESTAZIONI_GRUPPI (
  ID                INT NOT NULL,
  ID_UTE_INSERT     INT NOT NULL,
  DATA_INSERT       DATE NOT NULL,
  ID_UTE_UPDATE     INT,
  DATA_UPDATE       DATE,
  ID_UTE_DELETE     INT,
  DATA_DELETE       DATE,
  FLAG_ATTIVO       INT DEFAULT 1 NOT NULL,
  ID_GRU            INT NOT NULL,
  ID_AZI            INT,
  ID_FAR            INT,
  CODICE            VARCHAR(10) NOT NULL,
  DESCRIZIONE       VARCHAR(50) NOT NULL,
  CONSTRAINT PK_PRZ_PRESTAZIONI_GRUPPI PRIMARY KEY (ID) );

CREATE TABLE IF NOT EXISTS PRZ_PRESTAZIONI_TIPI (
  ID                INT NOT NULL,
  ID_UTE_INSERT     INT NOT NULL,
  DATA_INSERT       DATE NOT NULL,
  ID_UTE_UPDATE     INT,
  DATA_UPDATE       DATE,
  ID_UTE_DELETE     INT,
  DATA_DELETE       DATE,
  FLAG_ATTIVO       INT DEFAULT 1 NOT NULL,
  ID_GRU            INT NOT NULL,
  ID_AZI            INT,
  ID_FAR            INT,
  CODICE            VARCHAR(10) NOT NULL,
  DESCRIZIONE       VARCHAR(50) NOT NULL,
  CONSTRAINT PK_PRZ_PRESTAZIONI_TIPI PRIMARY KEY (ID) );

CREATE TABLE IF NOT EXISTS PRZ_PRESTAZIONI (
  ID                INT NOT NULL,
  ID_UTE_INSERT     INT NOT NULL,
  DATA_INSERT       DATE NOT NULL,
  ID_UTE_UPDATE     INT,
  DATA_UPDATE       DATE,
  ID_UTE_DELETE     INT,
  DATA_DELETE       DATE,
  FLAG_ATTIVO       INT DEFAULT 1 NOT NULL,
  ID_GRU            INT NOT NULL,
  ID_AZI            INT,
  ID_FAR            INT,
  ID_GRUPPO_PRE     INT DEFAULT 0 NOT NULL,
  ID_TIPO           INT DEFAULT 0 NOT NULL,
  COD_CSF           INT,
  COD_PROD          VARCHAR(9),
  DESCRIZIONE       VARCHAR(100),
  DURATA            INT,
  TIPO_PREZZO       VARCHAR(1)  DEFAULT 'F',
  PREN_ONLINE       INT DEFAULT 1 NOT NULL,
  FLAG_POSA         INT DEFAULT 0 NOT NULL,
  POSA_DAL_MIN      INT,
  POSA_AL_MIN       INT,
  PREZZO_LISTINO    FLOAT(10,4),
  SCONTO_PERC       FLOAT(4,2),
  SCONTO_ASS        FLOAT(10,4),
  PREZZO_FINALE     FLOAT(10,4),
  AVVERTENZE        VARCHAR(255),
  INDICAZIONI       VARCHAR(255),
  PUNTI_COLLAB      INT,
  CONSTRAINT PK_PRZ_PRESTAZIONI PRIMARY KEY (ID),
  CONSTRAINT FK_PRZ_PRE_GRU FOREIGN KEY (ID_GRUPPO_PRE) REFERENCES PRZ_PRESTAZIONI_GRUPPI(ID),
  CONSTRAINT FK_PRZ_PRE_TIP FOREIGN KEY (ID_TIPO) REFERENCES PRZ_PRESTAZIONI_TIPI(ID) );

CREATE TABLE IF NOT EXISTS PRZ_PRESTAZIONI_ATTREZ (
  ID                INT NOT NULL,
  ID_UTE_INSERT     INT NOT NULL,
  DATA_INSERT       DATE NOT NULL,
  ID_UTE_UPDATE     INT,
  DATA_UPDATE       DATE,
  ID_UTE_DELETE     INT,
  DATA_DELETE       DATE,
  FLAG_ATTIVO       INT  DEFAULT 1 NOT NULL,
  ID_PRESTAZIONE    INT,
  ID_ATTREZZATURA   INT,
  CONSTRAINT PK_PRZ_PRESTAZIONI_ATTREZ PRIMARY KEY (ID),
  CONSTRAINT FK_PRZ_PRE_ATT_PRE FOREIGN KEY (ID_PRESTAZIONE) REFERENCES PRZ_PRESTAZIONI(ID),
  CONSTRAINT FK_PRZ_PRE_ATT_ATT FOREIGN KEY (ID_ATTREZZATURA) REFERENCES PRZ_ATTREZZATURE(ID) );

CREATE TABLE IF NOT EXISTS PRZ_COLLABORATORI_PRE (
  ID                INT NOT NULL,
  ID_UTE_INSERT     INT NOT NULL,
  DATA_INSERT       DATE NOT NULL,
  ID_UTE_UPDATE     INT,
  DATA_UPDATE       DATE,
  ID_UTE_DELETE     INT,
  DATA_DELETE       DATE,
  FLAG_ATTIVO       INT DEFAULT 1 NOT NULL,
  ID_COLLABORATORE  INT,
  ID_PRESTAZIONE    INT,
  CONSTRAINT PK_PRZ_COLLABORATORI_PRE PRIMARY KEY (ID),
  CONSTRAINT FK_PRZ_PRE_COL_COL FOREIGN KEY (ID_COLLABORATORE) REFERENCES PRZ_COLLABORATORI(ID),
  CONSTRAINT FK_PRZ_PRE_COL_PRE FOREIGN KEY (ID_PRESTAZIONE) REFERENCES PRZ_PRESTAZIONI(ID) );

CREATE TABLE IF NOT EXISTS PRZ_AGENDE (
  ID                INT  NOT NULL,
  ID_UTE_INSERT     INT  NOT NULL,
  DATA_INSERT       DATE NOT NULL,
  ID_UTE_UPDATE     INT,
  DATA_UPDATE       DATE,
  ID_UTE_DELETE     INT,
  DATA_DELETE       DATE,
  FLAG_ATTIVO       INT DEFAULT 1 NOT NULL,
  ID_GRU            INT NOT NULL,
  ID_AZI            INT,
  ID_FAR            INT,
  ID_COLLABORATORE  INT NOT NULL,
  DESCRIZIONE       VARCHAR(100) NOT NULL,
  GIORNI            VARCHAR(7)   NOT NULL,
  SETTIMANE_ALT     INT  DEFAULT 0 NOT NULL,
  INIZIO_VALIDITA   DATE NOT NULL,
  FINE_VALIDITA     DATE,
  CONSTRAINT PK_PRZ_AGENDE PRIMARY KEY (ID),
  CONSTRAINT FK_PRZ_AGE_COL FOREIGN KEY (ID_COLLABORATORE) REFERENCES PRZ_COLLABORATORI(ID) );

CREATE TABLE IF NOT EXISTS PRZ_AGENDE_MODELLI (
  ID                INT NOT NULL,
  ID_UTE_INSERT     INT NOT NULL,
  DATA_INSERT       DATE NOT NULL,
  ID_UTE_UPDATE     INT,
  DATA_UPDATE       DATE,
  ID_UTE_DELETE     INT,
  DATA_DELETE       DATE,
  FLAG_ATTIVO       INT DEFAULT 1 NOT NULL,
  ID_AGENDA         INT NOT NULL,
  SETTIMANA_PARI    INT DEFAULT 1 NOT NULL,
  SETTIMANA_DISP    INT DEFAULT 1 NOT NULL,
  GIORNO            INT,
  PROGRESSIVO       INT,
  ORAINIZIO         INT,
  ORAFINE           INT,
  TIPOLOGIA         VARCHAR(1),
  VALORE            INT,
  PREN_ONLINE       INT DEFAULT 0 NOT NULL,
  CONSTRAINT PK_PRZ_AGENDE_MODELLI PRIMARY KEY (ID),
  CONSTRAINT FK_PRZ_AGE_MOD_AGE FOREIGN KEY (ID_AGENDA) REFERENCES PRZ_AGENDE(ID) );

CREATE TABLE IF NOT EXISTS PRZ_CALENDARIO (
  ID                INT NOT NULL,
  ID_UTE_INSERT     INT NOT NULL,
  DATA_INSERT       DATE NOT NULL,
  ID_UTE_UPDATE     INT,
  DATA_UPDATE       DATE,
  ID_UTE_DELETE     INT,
  DATA_DELETE       DATE,
  FLAG_ATTIVO       INT DEFAULT 1 NOT NULL,
  ID_GRU            INT NOT NULL,
  ID_AZI            INT,
  ID_FAR            INT,
  ID_COLLABORATORE  INT NOT NULL,
  ID_AGENDA         INT NOT NULL,
  ID_AGENDA_MODELLO INT NOT NULL,
  DATA_CALENDARIO   DATE,
  GIORNO            INT,
  PROGRESSIVO       INT,
  ORAINIZIO         INT,
  ORAFINE           INT,
  TIPOLOGIA         VARCHAR(1),
  MODELLO           TEXT,
  MINUTI            INT,
  POSTI             INT,
  MAX_CONSECUTIVI   INT,
  PREN_ONLINE       INT DEFAULT 0 NOT NULL,
  STATO             VARCHAR(1) NOT NULL,
  FLAG_VARIAZIONE   INT  DEFAULT 0 NOT NULL,
  CONSTRAINT PK_PRZ_CALENDARIO PRIMARY KEY (ID),
  CONSTRAINT FK_PRZ_CAL_COL FOREIGN KEY (ID_COLLABORATORE) REFERENCES PRZ_COLLABORATORI(ID) );

CREATE TABLE IF NOT EXISTS PRZ_CALENDARIO_VARIAZ (
  ID                INT NOT NULL,
  ID_UTE_INSERT     INT NOT NULL,
  DATA_INSERT       DATE NOT NULL,
  ID_UTE_UPDATE     INT,
  DATA_UPDATE       DATE,
  ID_UTE_DELETE     INT,
  DATA_DELETE       DATE,
  FLAG_ATTIVO       INT DEFAULT 1 NOT NULL,
  ID_GRU            INT NOT NULL,
  ID_AZI            INT,
  ID_FAR            INT,
  ID_COLLABORATORE  INT NOT NULL,
  DATA_CALENDARIO   DATE NOT NULL,
  GIORNO            INT,
  PROGRESSIVO       INT,
  ORAINIZIO         INT,
  ORAFINE           INT,
  TIPOLOGIA         VARCHAR(1),
  VALORE            INT,
  PREN_ONLINE       INT DEFAULT 0 NOT NULL,
  STATO             VARCHAR(1) NOT NULL,
  CONSTRAINT PK_PRZ_CALENDARIO_VARIAZ PRIMARY KEY (ID),
  CONSTRAINT FK_PRZ_CAL_VAR_COL FOREIGN KEY (ID_COLLABORATORE) REFERENCES PRZ_COLLABORATORI(ID) );

CREATE TABLE IF NOT EXISTS PRZ_CALENDARIO_CHIUSURE (
  ID                INT NOT NULL,
  ID_UTE_INSERT     INT NOT NULL,
  DATA_INSERT       DATE NOT NULL,
  ID_UTE_UPDATE     INT,
  DATA_UPDATE       DATE,
  ID_UTE_DELETE     INT,
  DATA_DELETE       DATE,
  FLAG_ATTIVO       INT DEFAULT 1 NOT NULL,
  ID_GRU            INT NOT NULL,
  ID_AZI            INT,
  ID_FAR            INT,
  DATA_CALENDARIO   DATE,
  MESE_GIORNO       INT,
  DESCRIZIONE       VARCHAR(50),
  CONSTRAINT PK_PRZ_CALENDARIO_CHIUSURE PRIMARY KEY (ID) );

CREATE TABLE IF NOT EXISTS PRZ_PRENOTAZIONI (
  ID                INT NOT NULL,
  ID_UTE_INSERT     INT NOT NULL,
  DATA_INSERT       DATE NOT NULL,
  ID_UTE_UPDATE     INT,
  DATA_UPDATE       DATE,
  ID_UTE_DELETE     INT,
  DATA_DELETE       DATE,
  FLAG_ATTIVO       INT DEFAULT 1 NOT NULL,
  ID_GRU            INT NOT NULL,
  ID_AZI            INT,
  ID_FAR            INT,
  CODICE            VARCHAR(30) NOT NULL,
  ID_CLIENTE        INT NOT NULL,
  ID_PRESTAZIONE    INT NOT NULL,
  ID_COLLABORATORE  INT NOT NULL,
  ID_ATTREZZATURA   INT,
  DATA_APPUNTAMENTO DATE NOT NULL,
  ORA_APPUNTAMENTO  INT  NOT NULL,
  GIORNO            INT  NOT NULL,
  DURATA            INT  NOT NULL,
  DATAORA_INIZIO    TIMESTAMP NOT NULL,
  DATAORA_FINE      TIMESTAMP NOT NULL,
  ID_AGENDA         INT,
  ID_AGENDA_MODELLO INT,
  PROGRESSIVO       INT,
  STATO             VARCHAR(1)    NOT NULL,
  NOTE              VARCHAR(255),
  PREN_ONLINE       INT DEFAULT 0 NOT NULL,
  FLAG_PAGATO       INT DEFAULT 0 NOT NULL,
  PREZZO_LISTINO    FLOAT(10,4),
  SCONTO_PERC       FLOAT(4,2),
  SCONTO_ASS        FLOAT(10,4),
  PREZZO_FINALE     FLOAT(10,4),
  OVERBOOKING       INT DEFAULT 0 NOT NULL,
  DATAORA_REMIND    TIMESTAMP,
  MARCATORE         INT,
  TIPO_APPUNTAMENTO VARCHAR(1),
  TIPO_PAGAMENTO    VARCHAR(1),
  IMPORTO_PAGATO    FLOAT(10,4),
  CODICE_COUPON     VARCHAR(30),
  CAUSALE           VARCHAR(50),
  UTENTE_DESK       VARCHAR(50),
  CONSTRAINT PK_PRZ_PRENOTAZIONI PRIMARY KEY (ID),
  CONSTRAINT FK_PRZ_PRN_CLI FOREIGN KEY (ID_CLIENTE)       REFERENCES PRZ_CLIENTI(ID),
  CONSTRAINT FK_PRZ_PRN_PRE FOREIGN KEY (ID_PRESTAZIONE)   REFERENCES PRZ_PRESTAZIONI(ID),
  CONSTRAINT FK_PRZ_PRN_COL FOREIGN KEY (ID_COLLABORATORE) REFERENCES PRZ_COLLABORATORI(ID),
  CONSTRAINT FK_PRZ_PRN_ATT FOREIGN KEY (ID_ATTREZZATURA)  REFERENCES PRZ_ATTREZZATURE(ID) );

CREATE TABLE IF NOT EXISTS PRZ_COMUNICAZIONI (
  ID                INT  NOT NULL,
  ID_UTE_INSERT     INT  NOT NULL,
  DATA_INSERT       DATE NOT NULL,
  ID_UTE_UPDATE     INT,
  DATA_UPDATE       DATE,
  ID_UTE_DELETE     INT,
  DATA_DELETE       DATE,
  FLAG_ATTIVO       INT   DEFAULT 1 NOT NULL,
  ID_GRU            INT  NOT NULL,
  ID_AZI            INT,
  ID_FAR            INT,
  OGGETTO           VARCHAR(100) NOT NULL,
  MESSAGGIO         VARCHAR(160) NOT NULL,
  MEZZO             VARCHAR(1),
  CONSTRAINT PK_PRZ_COMUNICAZIONI PRIMARY KEY (ID) );

CREATE TABLE IF NOT EXISTS PRZ_COMUNICAZIONI_CODA (
  ID_COMUNICAZIONE  INT  NOT NULL,
  ID_CLIENTE        INT  NOT NULL,
  DATA_ORA_INS      TIMESTAMP     NOT NULL,
  CONSTRAINT PK_PRZ_COMUNICAZIONI_CODA PRIMARY KEY (ID_COMUNICAZIONE,ID_CLIENTE) );

CREATE TABLE IF NOT EXISTS PRZ_LOG_SMS (
  ID                INT  NOT NULL,
  ID_UTE_INSERT     INT  NOT NULL,
  DATA_INSERT       DATE NOT NULL,
  ID_GRU            INT  NOT NULL,
  ID_AZI            INT,
  ID_FAR            INT,
  ID_CLIENTE        INT  NOT NULL,
  NUMERO            VARCHAR(15)   NOT NULL,
  MESSAGGIO         VARCHAR(160)  NOT NULL,
  INVIATO           INT DEFAULT 0 NOT NULL,
  RISPOSTA          VARCHAR(255),
  CONSTRAINT PK_PRZ_LOG_SMS PRIMARY KEY (ID) );

CREATE TABLE IF NOT EXISTS PRZ_UTENTI_DESK (
  ID                INT  NOT NULL,
  ID_UTE_INSERT     INT  NOT NULL,
  DATA_INSERT       DATE NOT NULL,
  ID_UTE_UPDATE     INT,
  DATA_UPDATE       DATE,
  ID_UTE_DELETE     INT,
  DATA_DELETE       DATE,
  FLAG_ATTIVO       INT DEFAULT 1 NOT NULL,
  ID_GRU            INT NOT NULL,
  ID_AZI            INT,
  ID_FAR            INT,
  USERNAME          VARCHAR(50)  NOT NULL,
  PASSWORD          VARCHAR(50)  NOT NULL,
  NOTE              VARCHAR(255),
  ABILITATO         INT DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PRZ_UTENTI_DESK PRIMARY KEY (ID) );

CREATE TABLE IF NOT EXISTS PRZ_LOG_OPERAZIONI (
  ID                INT  NOT NULL,
  DATA_INSERT       TIMESTAMP     NOT NULL,
  OPERAZIONE        VARCHAR(50)  NOT NULL,
  UTENTE_SIST       VARCHAR(50)  NOT NULL,
  UTENTE_DESK       VARCHAR(50),  
  ID_GRU            INT NOT NULL,
  ID_AZI            INT,
  ID_FAR            INT NOT NULL,
  ID_CLIENTE        INT DEFAULT 0 NOT NULL,
  ID_PRESTAZIONE    INT DEFAULT 0 NOT NULL,
  ID_COLLABORATORE  INT DEFAULT 0 NOT NULL,
  ID_ATTREZZATURA   INT DEFAULT 0 NOT NULL,
  ID_PRENOTAZIONE   INT DEFAULT 0 NOT NULL,
  ID_AGENDA         INT DEFAULT 0 NOT NULL,
  DATA_CALENDARIO   DATE,
  LOG_NOTE          VARCHAR(255),
  CONSTRAINT PK_PRZ_LOG_OPERAZIONI PRIMARY KEY (ID) );

--
-- Sequences
--

CREATE TABLE TAB_SEQUENCES (
  SEQ_NAME VARCHAR(50) NOT NULL,
  SEQ_VAL  INT NOT NULL,
  CONSTRAINT PK_TAB_SEQUENCES PRIMARY KEY (SEQ_NAME) );

--
-- Indexes
--

CREATE INDEX IDX_PRZ_CLI_COG ON PRZ_CLIENTI(COGNOME);
CREATE INDEX IDX_PRZ_CLI_CFI ON PRZ_CLIENTI(CODICE_FISCALE);
CREATE INDEX IDX_PRZ_PRN_CLI ON PRZ_PRENOTAZIONI(ID_CLIENTE);
CREATE INDEX IDX_PRZ_PRN_COD ON PRZ_PRENOTAZIONI(CODICE);
CREATE INDEX IDX_PRZ_PRN_DAP ON PRZ_PRENOTAZIONI(DATA_APPUNTAMENTO);
CREATE INDEX IDX_PRZ_PRN_CIF ON PRZ_PRENOTAZIONI(ID_COLLABORATORE,DATAORA_INIZIO,DATAORA_FINE);
CREATE INDEX IDX_PRZ_ARS_IDA ON PRZ_ATTREZZATURE_RIS(ID_ATTREZZATURA,RISERVATO_DAL,RISERVATO_AL);
CREATE INDEX IDX_PRZ_CAL_ICD ON PRZ_CALENDARIO(ID_COLLABORATORE,DATA_CALENDARIO);
CREATE INDEX IDX_PRZ_CVA_ICD ON PRZ_CALENDARIO_VARIAZ(ID_COLLABORATORE,DATA_CALENDARIO);
CREATE INDEX IDX_PRZ_UTE_USR ON PRZ_UTENTI_DESK(ID_GRU,USERNAME);
CREATE INDEX IDX_PRZ_UTE_PWD ON PRZ_UTENTI_DESK(ID_GRU,PASSWORD);
CREATE INDEX IDX_PRZ_LOG_DIN ON PRZ_LOG_OPERAZIONI(DATA_INSERT);
CREATE INDEX IDX_PRZ_LOG_IDP ON PRZ_LOG_OPERAZIONI(ID_PRENOTAZIONE);
CREATE INDEX IDX_PRZ_LOG_CAL ON PRZ_LOG_OPERAZIONI(DATA_CALENDARIO);

-- mysql --user=root --password[=password] bookme
-- source C:/prj/dew/bookme/mysql/03_schema.sql;
--
-- Check
--
-- show tables;
