CREATE TABLE PRZ_STRUTTURE (
	ID                NUMBER(10,0) NOT NULL,
	ID_UTE_INSERT     NUMBER(10,0) NOT NULL,
	DATA_INSERT       DATE NOT NULL,
	ID_UTE_UPDATE     NUMBER(10,0),
	DATA_UPDATE       DATE,
	ID_UTE_DELETE     NUMBER(10,0),
	DATA_DELETE       DATE,
	FLAG_ATTIVO       NUMBER(1,0)  DEFAULT 1 NOT NULL,
	ID_GRU            NUMBER(10,0) NOT NULL,
	ID_AZI            NUMBER(10,0),
	ID_FAR            NUMBER(10,0),
	CODICE            VARCHAR2(10) NOT NULL,
	DESCRIZIONE       VARCHAR2(50) NOT NULL,
	TELEFONO          VARCHAR2(15),
	EMAIL             VARCHAR2(100),
	PREN_ONLINE       NUMBER(1,0)  DEFAULT 0 NOT NULL,
	CHECK_USER_DESK   NUMBER(1,0)  DEFAULT 0 NOT NULL,
	CONSTRAINT PK_PRZ_STRUTTURE PRIMARY KEY (ID) );

CREATE TABLE PRZ_ATTREZZATURE (
	ID                NUMBER(10,0) NOT NULL,
	ID_UTE_INSERT     NUMBER(10,0) NOT NULL,
	DATA_INSERT       DATE NOT NULL,
	ID_UTE_UPDATE     NUMBER(10,0),
	DATA_UPDATE       DATE,
	ID_UTE_DELETE     NUMBER(10,0),
	DATA_DELETE       DATE,
	FLAG_ATTIVO       NUMBER(1,0)  DEFAULT 1 NOT NULL,
	ID_GRU            NUMBER(10,0) NOT NULL,
	ID_AZI            NUMBER(10,0),
	ID_FAR            NUMBER(10,0),
	CODICE            VARCHAR2(10) NOT NULL,
	DESCRIZIONE       VARCHAR2(50) NOT NULL,
	UBICAZIONE        VARCHAR2(100),
	CONSTRAINT PK_PRZ_ATTREZZATURE PRIMARY KEY (ID) );

CREATE TABLE PRZ_CLIENTI (
	ID                NUMBER(10,0) NOT NULL,
	ID_UTE_INSERT     NUMBER(10,0) NOT NULL,
	DATA_INSERT       DATE NOT NULL,
	ID_UTE_UPDATE     NUMBER(10,0),
	DATA_UPDATE       DATE,
	ID_UTE_DELETE     NUMBER(10,0),
	DATA_DELETE       DATE,
	FLAG_ATTIVO       NUMBER(1,0)  DEFAULT 1 NOT NULL,
	ID_GRU            NUMBER(10,0) NOT NULL,
	ID_AZI            NUMBER(10,0),
	ID_FAR            NUMBER(10,0),
	COGNOME           VARCHAR2(50) NOT NULL,
	NOME              VARCHAR2(50) NOT NULL,
	CODICE_FISCALE    VARCHAR2(16),
	SESSO             VARCHAR2(1),
	DATA_NASCITA      DATE,
	TELEFONO_1        VARCHAR2(18),
	TELEFONO_2        VARCHAR2(18),
	EMAIL             VARCHAR2(100),
	INDIRIZZO         VARCHAR2(100),
	CITTA             VARCHAR2(50),
	CAP               VARCHAR2(5),
	REPUTAZIONE       NUMBER(1),
	NOTE              VARCHAR2(255),
	ID_FIDELITY       NUMBER(10,0),
	UTENTE            VARCHAR2(50),
	PASSWORD          VARCHAR2(50),
	DIS_PREN_ONLINE   NUMBER(1,0),
	CONSTRAINT PK_PRZ_CLIENTI PRIMARY KEY (ID) );

CREATE TABLE PRZ_COLLABORATORI (
	ID                NUMBER(10,0) NOT NULL,
	ID_UTE_INSERT     NUMBER(10,0) NOT NULL,
	DATA_INSERT       DATE NOT NULL,
	ID_UTE_UPDATE     NUMBER(10,0),
	DATA_UPDATE       DATE,
	ID_UTE_DELETE     NUMBER(10,0),
	DATA_DELETE       DATE,
	FLAG_ATTIVO       NUMBER(1,0)  DEFAULT 1 NOT NULL,
	ID_GRU            NUMBER(10,0) NOT NULL,
	ID_AZI            NUMBER(10,0),
	ID_FAR            NUMBER(10,0),
	NOME              VARCHAR2(50) NOT NULL,
	COLORE            VARCHAR2(6)  NOT NULL,
	PREN_ONLINE       NUMBER(1,0)  DEFAULT 1 NOT NULL,
	ID_UTENTE         NUMBER(10,0),
	ORDINE            NUMBER(10,0) DEFAULT 0,
	VISIBILE          NUMBER(1,0)  DEFAULT 1 NOT NULL,
	CONSTRAINT PK_PRZ_COLLABORATORI PRIMARY KEY (ID) );

CREATE TABLE PRZ_ATTREZZATURE_RIS (
	ID                NUMBER(10,0) NOT NULL,
	ID_UTE_INSERT     NUMBER(10,0) NOT NULL,
	DATA_INSERT       DATE NOT NULL,
	ID_UTE_UPDATE     NUMBER(10,0),
	DATA_UPDATE       DATE,
	ID_UTE_DELETE     NUMBER(10,0),
	DATA_DELETE       DATE,
	FLAG_ATTIVO       NUMBER(1,0)  DEFAULT 1 NOT NULL,
	ID_ATTREZZATURA   NUMBER(10,0),
	ID_COLLABORATORE  NUMBER(10,0),
	RISERVATO_DAL     TIMESTAMP,
	RISERVATO_AL      TIMESTAMP,
	CONSTRAINT PK_PRZ_ATTREZZATURE_RIS PRIMARY KEY (ID),
	CONSTRAINT FK_PRZ_ATT_RIS_ATT FOREIGN KEY (ID_ATTREZZATURA) REFERENCES PRZ_ATTREZZATURE(ID),
	CONSTRAINT FK_PRZ_ATT_RIS_COL FOREIGN KEY (ID_COLLABORATORE) REFERENCES PRZ_COLLABORATORI(ID) );

CREATE TABLE PRZ_PRESTAZIONI_GRUPPI (
	ID                NUMBER(10,0) NOT NULL,
	ID_UTE_INSERT     NUMBER(10,0) NOT NULL,
	DATA_INSERT       DATE NOT NULL,
	ID_UTE_UPDATE     NUMBER(10,0),
	DATA_UPDATE       DATE,
	ID_UTE_DELETE     NUMBER(10,0),
	DATA_DELETE       DATE,
	FLAG_ATTIVO       NUMBER(1,0)  DEFAULT 1 NOT NULL,
	ID_GRU            NUMBER(10,0) NOT NULL,
	ID_AZI            NUMBER(10,0),
	ID_FAR            NUMBER(10,0),
	CODICE            VARCHAR2(10) NOT NULL,
	DESCRIZIONE       VARCHAR2(50) NOT NULL,
	CONSTRAINT PK_PRZ_PRESTAZIONI_GRUPPI PRIMARY KEY (ID) );

CREATE TABLE PRZ_PRESTAZIONI_TIPI (
	ID                NUMBER(10,0) NOT NULL,
	ID_UTE_INSERT     NUMBER(10,0) NOT NULL,
	DATA_INSERT       DATE NOT NULL,
	ID_UTE_UPDATE     NUMBER(10,0),
	DATA_UPDATE       DATE,
	ID_UTE_DELETE     NUMBER(10,0),
	DATA_DELETE       DATE,
	FLAG_ATTIVO       NUMBER(1,0)  DEFAULT 1 NOT NULL,
	ID_GRU            NUMBER(10,0) NOT NULL,
	ID_AZI            NUMBER(10,0),
	ID_FAR            NUMBER(10,0),
	CODICE            VARCHAR2(10) NOT NULL,
	DESCRIZIONE       VARCHAR2(50) NOT NULL,
	CONSTRAINT PK_PRZ_PRESTAZIONI_TIPI PRIMARY KEY (ID) );

CREATE TABLE PRZ_PRESTAZIONI (
	ID                NUMBER(10,0) NOT NULL,
	ID_UTE_INSERT     NUMBER(10,0) NOT NULL,
	DATA_INSERT       DATE NOT NULL,
	ID_UTE_UPDATE     NUMBER(10,0),
	DATA_UPDATE       DATE,
	ID_UTE_DELETE     NUMBER(10,0),
	DATA_DELETE       DATE,
	FLAG_ATTIVO       NUMBER(1,0)  DEFAULT 1 NOT NULL,
	ID_GRU            NUMBER(10,0) NOT NULL,
	ID_AZI            NUMBER(10,0),
	ID_FAR            NUMBER(10,0),
	ID_GRUPPO_PRE     NUMBER(10,0) DEFAULT 0 NOT NULL,
	ID_TIPO           NUMBER(10,0) DEFAULT 0 NOT NULL,
	COD_CSF           NUMBER(10,0),
	COD_PROD          VARCHAR2(9),
	DESCRIZIONE       VARCHAR2(100),
	DURATA            NUMBER(4),
	TIPO_PREZZO       VARCHAR2(1)  DEFAULT 'F',
	PREN_ONLINE       NUMBER(1,0)  DEFAULT 1 NOT NULL,
	FLAG_POSA         NUMBER(1,0)  DEFAULT 0 NOT NULL,
	POSA_DAL_MIN      NUMBER(4),
	POSA_AL_MIN       NUMBER(4),
	PREZZO_LISTINO    NUMBER(10,4),
	SCONTO_PERC       NUMBER(4,2),
	SCONTO_ASS        NUMBER(10,4),
	PREZZO_FINALE     NUMBER(10,4),
	AVVERTENZE        VARCHAR2(255),
	INDICAZIONI       VARCHAR2(255),
	PUNTI_OPERATORE   NUMBER(10,0),
	CONSTRAINT PK_PRZ_PRESTAZIONI PRIMARY KEY (ID),
	CONSTRAINT FK_PRZ_PRE_GRU FOREIGN KEY (ID_GRUPPO_PRE) REFERENCES PRZ_PRESTAZIONI_GRUPPI(ID),
	CONSTRAINT FK_PRZ_PRE_TIP FOREIGN KEY (ID_TIPO) REFERENCES PRZ_PRESTAZIONI_TIPI(ID) );

CREATE TABLE PRZ_PRESTAZIONI_ATTREZ (
	ID                NUMBER(10,0) NOT NULL,
	ID_UTE_INSERT     NUMBER(10,0) NOT NULL,
	DATA_INSERT       DATE NOT NULL,
	ID_UTE_UPDATE     NUMBER(10,0),
	DATA_UPDATE       DATE,
	ID_UTE_DELETE     NUMBER(10,0),
	DATA_DELETE       DATE,
	FLAG_ATTIVO       NUMBER(1,0)  DEFAULT 1 NOT NULL,
	ID_PRESTAZIONE    NUMBER(10,0),
	ID_ATTREZZATURA   NUMBER(10,0),
	CONSTRAINT PK_PRZ_PRESTAZIONI_ATTREZ PRIMARY KEY (ID),
	CONSTRAINT FK_PRZ_PRE_ATT_PRE FOREIGN KEY (ID_PRESTAZIONE) REFERENCES PRZ_PRESTAZIONI(ID),
	CONSTRAINT FK_PRZ_PRE_ATT_ATT FOREIGN KEY (ID_ATTREZZATURA) REFERENCES PRZ_ATTREZZATURE(ID) );

CREATE TABLE PRZ_COLLABORATORI_PRE (
	ID                NUMBER(10,0) NOT NULL,
	ID_UTE_INSERT     NUMBER(10,0) NOT NULL,
	DATA_INSERT       DATE NOT NULL,
	ID_UTE_UPDATE     NUMBER(10,0),
	DATA_UPDATE       DATE,
	ID_UTE_DELETE     NUMBER(10,0),
	DATA_DELETE       DATE,
	FLAG_ATTIVO       NUMBER(1,0)  DEFAULT 1 NOT NULL,
	ID_COLLABORATORE  NUMBER(10,0),
	ID_PRESTAZIONE    NUMBER(10,0),
	CONSTRAINT PK_PRZ_COLLABORATORI_PRE PRIMARY KEY (ID),
	CONSTRAINT FK_PRZ_PRE_COL_COL FOREIGN KEY (ID_COLLABORATORE) REFERENCES PRZ_COLLABORATORI(ID),
	CONSTRAINT FK_PRZ_PRE_COL_PRE FOREIGN KEY (ID_PRESTAZIONE) REFERENCES PRZ_PRESTAZIONI(ID) );

CREATE TABLE PRZ_AGENDE (
	ID                NUMBER(10,0)  NOT NULL,
	ID_UTE_INSERT     NUMBER(10,0)  NOT NULL,
	DATA_INSERT       DATE NOT NULL,
	ID_UTE_UPDATE     NUMBER(10,0),
	DATA_UPDATE       DATE,
	ID_UTE_DELETE     NUMBER(10,0),
	DATA_DELETE       DATE,
	FLAG_ATTIVO       NUMBER(1,0)   DEFAULT 1 NOT NULL,
	ID_GRU            NUMBER(10,0)  NOT NULL,
	ID_AZI            NUMBER(10,0),
	ID_FAR            NUMBER(10,0),
	ID_COLLABORATORE  NUMBER(10,0)  NOT NULL,
	DESCRIZIONE       VARCHAR2(100) NOT NULL,
	GIORNI            VARCHAR2(7)   NOT NULL,
	SETTIMANE_ALT     NUMBER(1,0)   DEFAULT 0 NOT NULL,
	INIZIO_VALIDITA   DATE NOT NULL,
	FINE_VALIDITA     DATE,
	CONSTRAINT PK_PRZ_AGENDE PRIMARY KEY (ID),
	CONSTRAINT FK_PRZ_AGE_COL FOREIGN KEY (ID_COLLABORATORE) REFERENCES PRZ_COLLABORATORI(ID) );

CREATE TABLE PRZ_AGENDE_MODELLI (
	ID                NUMBER(10,0) NOT NULL,
	ID_UTE_INSERT     NUMBER(10,0) NOT NULL,
	DATA_INSERT       DATE NOT NULL,
	ID_UTE_UPDATE     NUMBER(10,0),
	DATA_UPDATE       DATE,
	ID_UTE_DELETE     NUMBER(10,0),
	DATA_DELETE       DATE,
	FLAG_ATTIVO       NUMBER(1,0)  DEFAULT 1 NOT NULL,
	ID_AGENDA         NUMBER(10,0) NOT NULL,
	SETTIMANA_PARI    NUMBER(1,0)  DEFAULT 1 NOT NULL,
	SETTIMANA_DISP    NUMBER(1,0)  DEFAULT 1 NOT NULL,
	GIORNO            NUMBER(1,0),
	PROGRESSIVO       NUMBER(5),
	ORAINIZIO         NUMBER(4),
	ORAFINE           NUMBER(4),
	TIPOLOGIA         VARCHAR2(1),
	VALORE            NUMBER(4),
	PREN_ONLINE       NUMBER(1,0) DEFAULT 0 NOT NULL,
	CONSTRAINT PK_PRZ_AGENDE_MODELLI PRIMARY KEY (ID),
	CONSTRAINT FK_PRZ_AGE_MOD_AGE FOREIGN KEY (ID_AGENDA) REFERENCES PRZ_AGENDE(ID) );

CREATE TABLE PRZ_CALENDARIO (
	ID                NUMBER(10,0) NOT NULL,
	ID_UTE_INSERT     NUMBER(10,0) NOT NULL,
	DATA_INSERT       DATE NOT NULL,
	ID_UTE_UPDATE     NUMBER(10,0),
	DATA_UPDATE       DATE,
	ID_UTE_DELETE     NUMBER(10,0),
	DATA_DELETE       DATE,
	FLAG_ATTIVO       NUMBER(1,0)  DEFAULT 1 NOT NULL,
	ID_GRU            NUMBER(10,0) NOT NULL,
	ID_AZI            NUMBER(10,0),
	ID_FAR            NUMBER(10,0),
	ID_COLLABORATORE  NUMBER(10,0) NOT NULL,
	ID_AGENDA         NUMBER(10,0) NOT NULL,
	ID_AGENDA_MODELLO NUMBER(10,0) NOT NULL,
	DATA_CALENDARIO   DATE,
	GIORNO            NUMBER(1,0),
	PROGRESSIVO       NUMBER(5),
	ORAINIZIO         NUMBER(4),
	ORAFINE           NUMBER(4),
	TIPOLOGIA         VARCHAR2(1),
	MODELLO           VARCHAR2(1440),
	MINUTI            NUMBER(4),
	POSTI             NUMBER(4),
	MAX_CONSECUTIVI   NUMBER(4,0),
	PREN_ONLINE       NUMBER(1,0) DEFAULT 0 NOT NULL,
	STATO             VARCHAR2(1) NOT NULL,
	FLAG_VARIAZIONE   NUMBER(1,0)  DEFAULT 0 NOT NULL,
	CONSTRAINT PK_PRZ_CALENDARIO PRIMARY KEY (ID),
	CONSTRAINT FK_PRZ_CAL_COL FOREIGN KEY (ID_COLLABORATORE) REFERENCES PRZ_COLLABORATORI(ID) );

CREATE TABLE PRZ_CALENDARIO_VARIAZ (
	ID                NUMBER(10,0) NOT NULL,
	ID_UTE_INSERT     NUMBER(10,0) NOT NULL,
	DATA_INSERT       DATE NOT NULL,
	ID_UTE_UPDATE     NUMBER(10,0),
	DATA_UPDATE       DATE,
	ID_UTE_DELETE     NUMBER(10,0),
	DATA_DELETE       DATE,
	FLAG_ATTIVO       NUMBER(1,0)  DEFAULT 1 NOT NULL,
	ID_GRU            NUMBER(10,0) NOT NULL,
	ID_AZI            NUMBER(10,0),
	ID_FAR            NUMBER(10,0),
	ID_COLLABORATORE  NUMBER(10,0) NOT NULL,
	DATA_CALENDARIO   DATE NOT NULL,
	GIORNO            NUMBER(1,0),
	PROGRESSIVO       NUMBER(5),
	ORAINIZIO         NUMBER(4),
	ORAFINE           NUMBER(4),
	TIPOLOGIA         VARCHAR2(1),
	VALORE            NUMBER(4),
	PREN_ONLINE       NUMBER(1,0) DEFAULT 0 NOT NULL,
	STATO             VARCHAR2(1) NOT NULL,
	CONSTRAINT PK_PRZ_CALENDARIO_VARIAZ PRIMARY KEY (ID),
	CONSTRAINT FK_PRZ_CAL_VAR_COL FOREIGN KEY (ID_COLLABORATORE) REFERENCES PRZ_COLLABORATORI(ID) );

CREATE TABLE PRZ_CALENDARIO_CHIUSURE (
	ID                NUMBER(10,0) NOT NULL,
	ID_UTE_INSERT     NUMBER(10,0) NOT NULL,
	DATA_INSERT       DATE NOT NULL,
	ID_UTE_UPDATE     NUMBER(10,0),
	DATA_UPDATE       DATE,
	ID_UTE_DELETE     NUMBER(10,0),
	DATA_DELETE       DATE,
	FLAG_ATTIVO       NUMBER(1,0)  DEFAULT 1 NOT NULL,
	ID_GRU            NUMBER(10,0) NOT NULL,
	ID_AZI            NUMBER(10,0),
	ID_FAR            NUMBER(10,0),
	DATA_CALENDARIO   DATE,
	MESE_GIORNO       NUMBER(4,0),
	DESCRIZIONE       VARCHAR2(50),
	CONSTRAINT PK_PRZ_CALENDARIO_CHIUSURE PRIMARY KEY (ID) );

CREATE TABLE PRZ_PRENOTAZIONI (
	ID                NUMBER(10,0) NOT NULL,
	ID_UTE_INSERT     NUMBER(10,0) NOT NULL,
	DATA_INSERT       DATE NOT NULL,
	ID_UTE_UPDATE     NUMBER(10,0),
	DATA_UPDATE       DATE,
	ID_UTE_DELETE     NUMBER(10,0),
	DATA_DELETE       DATE,
	FLAG_ATTIVO       NUMBER(1,0)  DEFAULT 1 NOT NULL,
	ID_GRU            NUMBER(10,0) NOT NULL,
	ID_AZI            NUMBER(10,0),
	ID_FAR            NUMBER(10,0),
	CODICE            VARCHAR2(30) NOT NULL,
	ID_CLIENTE        NUMBER(10,0) NOT NULL,
	ID_PRESTAZIONE    NUMBER(10,0) NOT NULL,
	ID_COLLABORATORE  NUMBER(10,0) NOT NULL,
	ID_ATTREZZATURA   NUMBER(10,0),
	DATA_APPUNTAMENTO DATE         NOT NULL,
	ORA_APPUNTAMENTO  NUMBER(4,0)  NOT NULL,
	GIORNO            NUMBER(1,0)  NOT NULL,
	DURATA            NUMBER(4,0)  NOT NULL,
	DATAORA_INIZIO    TIMESTAMP    NOT NULL,
	DATAORA_FINE      TIMESTAMP    NOT NULL,
	ID_AGENDA         NUMBER(10,0),
	ID_AGENDA_MODELLO NUMBER(10,0),
	PROGRESSIVO       NUMBER(5),
	STATO             VARCHAR2(1)  NOT NULL,
	NOTE              VARCHAR2(255),
	PREN_ONLINE       NUMBER(1,0) DEFAULT 0 NOT NULL,
	FLAG_PAGATO       NUMBER(1,0) DEFAULT 0 NOT NULL,
	PREZZO_LISTINO    NUMBER(10,4),
	SCONTO_PERC       NUMBER(4,2),
	SCONTO_ASS        NUMBER(10,4),
	PREZZO_FINALE     NUMBER(10,4),
	OVERBOOKING       NUMBER(1,0) DEFAULT 0 NOT NULL,
	DATAORA_REMIND    TIMESTAMP,
	MARCATORE         NUMBER(10,0),
	TIPO_APPUNTAMENTO VARCHAR2(1),
	TIPO_PAGAMENTO    VARCHAR2(1),
	IMPORTO_PAGATO    NUMBER(10,4),
	CODICE_COUPON     VARCHAR2(30),
	CAUSALE           VARCHAR2(50),
	UTENTE_DESK       VARCHAR2(50),
	CONSTRAINT PK_PRZ_PRENOTAZIONI PRIMARY KEY (ID),
	CONSTRAINT FK_PRZ_PRN_CLI FOREIGN KEY (ID_CLIENTE) REFERENCES PRZ_CLIENTI(ID),
	CONSTRAINT FK_PRZ_PRN_PRE FOREIGN KEY (ID_PRESTAZIONE) REFERENCES PRZ_PRESTAZIONI(ID),
	CONSTRAINT FK_PRZ_PRN_COL FOREIGN KEY (ID_COLLABORATORE) REFERENCES PRZ_COLLABORATORI(ID),
	CONSTRAINT FK_PRZ_PRN_ATT FOREIGN KEY (ID_ATTREZZATURA) REFERENCES PRZ_ATTREZZATURE(ID) );

CREATE TABLE PRZ_COMUNICAZIONI (
	ID                NUMBER(10,0)  NOT NULL,
	ID_UTE_INSERT     NUMBER(10,0)  NOT NULL,
	DATA_INSERT       DATE NOT NULL,
	ID_UTE_UPDATE     NUMBER(10,0),
	DATA_UPDATE       DATE,
	ID_UTE_DELETE     NUMBER(10,0),
	DATA_DELETE       DATE,
	FLAG_ATTIVO       NUMBER(1,0)   DEFAULT 1 NOT NULL,
	ID_GRU            NUMBER(10,0)  NOT NULL,
	ID_AZI            NUMBER(10,0),
	ID_FAR            NUMBER(10,0),
	OGGETTO           VARCHAR2(100) NOT NULL,
	MESSAGGIO         VARCHAR2(160) NOT NULL,
	MEZZO             VARCHAR2(1),
	CONSTRAINT PK_PRZ_COMUNICAZIONI PRIMARY KEY (ID) );

CREATE TABLE PRZ_COMUNICAZIONI_CODA (
	ID_COMUNICAZIONE  NUMBER(10,0)  NOT NULL,
	ID_CLIENTE        NUMBER(10,0)  NOT NULL,
	DATA_ORA_INS      TIMESTAMP     NOT NULL,
	CONSTRAINT PK_PRZ_COMUNICAZIONI_CODA PRIMARY KEY (ID_COMUNICAZIONE,ID_CLIENTE) );

CREATE TABLE PRZ_LOG_SMS (
	ID                NUMBER(10,0)  NOT NULL,
	ID_UTE_INSERT     NUMBER(10,0)  NOT NULL,
	DATA_INSERT       DATE NOT NULL,
	ID_GRU            NUMBER(10,0)  NOT NULL,
	ID_AZI            NUMBER(10,0),
	ID_FAR            NUMBER(10,0),
	ID_CLIENTE        NUMBER(10,0)  NOT NULL,
	NUMERO            VARCHAR2(15)  NOT NULL,
	MESSAGGIO         VARCHAR2(160) NOT NULL,
	INVIATO           NUMBER(1,0) DEFAULT 0 NOT NULL,
	RISPOSTA          VARCHAR2(255),
	CONSTRAINT PK_PRZ_LOG_SMS PRIMARY KEY (ID) );

CREATE TABLE PRZ_UTENTI_DESK (
	ID                NUMBER(10,0)  NOT NULL,
	ID_UTE_INSERT     NUMBER(10,0)  NOT NULL,
	DATA_INSERT       DATE NOT NULL,
	ID_UTE_UPDATE     NUMBER(10,0),
	DATA_UPDATE       DATE,
	ID_UTE_DELETE     NUMBER(10,0),
	DATA_DELETE       DATE,
	FLAG_ATTIVO       NUMBER(1,0)   DEFAULT 1 NOT NULL,
	ID_GRU            NUMBER(10,0)  NOT NULL,
	ID_AZI            NUMBER(10,0),
	ID_FAR            NUMBER(10,0),
	USERNAME          VARCHAR2(50)  NOT NULL,
	PASSWORD          VARCHAR2(50)  NOT NULL,
	NOTE              VARCHAR2(255),
	ABILITATO         NUMBER(1,0)   DEFAULT 1 NOT NULL,
	CONSTRAINT PK_PRZ_UTENTI_DESK PRIMARY KEY (ID) );

CREATE TABLE PRZ_LOG_OPERAZIONI (
	ID                NUMBER(10,0)  NOT NULL,
	DATA_INSERT       TIMESTAMP     NOT NULL,
	OPERAZIONE        VARCHAR2(50)  NOT NULL,
	UTENTE_SIST       VARCHAR2(50)  NOT NULL,
	UTENTE_DESK       VARCHAR2(50),  
	ID_GRU            NUMBER(10,0)  NOT NULL,
	ID_AZI            NUMBER(10,0),
	ID_FAR            NUMBER(10,0)  NOT NULL,
	ID_CLIENTE        NUMBER(10,0)  DEFAULT 0 NOT NULL,
	ID_PRESTAZIONE    NUMBER(10,0)  DEFAULT 0 NOT NULL,
	ID_COLLABORATORE  NUMBER(10,0)  DEFAULT 0 NOT NULL,
	ID_ATTREZZATURA   NUMBER(10,0)  DEFAULT 0 NOT NULL,
	ID_PRENOTAZIONE   NUMBER(10,0)  DEFAULT 0 NOT NULL,
	ID_AGENDA         NUMBER(10,0)  DEFAULT 0 NOT NULL,
	DATA_CALENDARIO   DATE,
	NOTE              VARCHAR2(255),
	CONSTRAINT PK_PRZ_LOG_OPERAZIONI PRIMARY KEY (ID) );

CREATE SEQUENCE SEQ_PRZ_STRUTTURE           START WITH 1 MAXVALUE 999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_PRZ_ATTREZZATURE        START WITH 1 MAXVALUE 999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_PRZ_CLIENTI             START WITH 1 MAXVALUE 999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_PRZ_COLLABORATORI       START WITH 1 MAXVALUE 999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_PRZ_ATTREZZATURE_RIS    START WITH 1 MAXVALUE 999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_PRZ_PRESTAZIONI_GRUPPI  START WITH 1 MAXVALUE 999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_PRZ_PRESTAZIONI_TIPI    START WITH 1 MAXVALUE 999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_PRZ_PRESTAZIONI         START WITH 1 MAXVALUE 999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_PRZ_PRESTAZIONI_ATTREZ  START WITH 1 MAXVALUE 999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_PRZ_COLLABORATORI_PRE   START WITH 1 MAXVALUE 999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_PRZ_AGENDE              START WITH 1 MAXVALUE 999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_PRZ_AGENDE_MODELLI      START WITH 1 MAXVALUE 999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_PRZ_CALENDARIO          START WITH 1 MAXVALUE 999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_PRZ_CALENDARIO_VARIAZ   START WITH 1 MAXVALUE 999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_PRZ_CALENDARIO_CHIUSURE START WITH 1 MAXVALUE 999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_PRZ_PRENOTAZIONI        START WITH 1 MAXVALUE 999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_PRZ_COMUNICAZIONI       START WITH 1 MAXVALUE 999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_PRZ_LOG_SMS             START WITH 1 MAXVALUE 999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_PRZ_UTENTI_DESK         START WITH 1 MAXVALUE 999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_PRZ_LOG_OPERAZIONI      START WITH 1 MAXVALUE 999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;

CREATE INDEX IDX_PRZ_CLI_COG  ON PRZ_CLIENTI(COGNOME);
CREATE INDEX IDX_PRZ_CLI_CFI  ON PRZ_CLIENTI(CODICE_FISCALE);
CREATE INDEX IDX_PRZ_PRN_CLI  ON PRZ_PRENOTAZIONI(ID_CLIENTE);
CREATE INDEX IDX_PRZ_PRN_COD  ON PRZ_PRENOTAZIONI(CODICE);
CREATE INDEX IDX_PRZ_PRN_DAP  ON PRZ_PRENOTAZIONI(DATA_APPUNTAMENTO);
CREATE INDEX IDX_PRZ_PRN_CIF  ON PRZ_PRENOTAZIONI(ID_COLLABORATORE,DATAORA_INIZIO,DATAORA_FINE);
CREATE INDEX IDX_PRZ_ARS_IDA  ON PRZ_ATTREZZATURE_RIS(ID_ATTREZZATURA,RISERVATO_DAL,RISERVATO_AL);
CREATE INDEX IDX_PRZ_CAL_ICD  ON PRZ_CALENDARIO(ID_COLLABORATORE,DATA_CALENDARIO);
CREATE INDEX IDX_PRZ_CVA_ICD  ON PRZ_CALENDARIO_VARIAZ(ID_COLLABORATORE,DATA_CALENDARIO);
CREATE INDEX IDX_PRZ_UTE_USR  ON PRZ_UTENTI_DESK(ID_GRU,USERNAME);
CREATE INDEX IDX_PRZ_UTE_PWD  ON PRZ_UTENTI_DESK(ID_GRU,PASSWORD);
CREATE INDEX IDX_PRZ_LOG_DIN  ON PRZ_LOG_OPERAZIONI(DATA_INSERT);
CREATE INDEX IDX_PRZ_LOG_IDP  ON PRZ_LOG_OPERAZIONI(ID_PRENOTAZIONE);
CREATE INDEX IDX_PRZ_LOG_CAL  ON PRZ_LOG_OPERAZIONI(DATA_CALENDARIO);

